name: Build and push image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime image'
        required: true
        default: 'hackmdio/runtime:16.20.2-35fe7e39'
      buildpack:
        description: 'Buildpack image'
        required: true
        default: 'hackmdio/buildpack:16.20.2-35fe7e39'

env:
  REGISTRY_IMAGE: lamprosfasoulas/codimd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        run: echo "PLATFORM_PAIR=linux-amd64" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployments/Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest
            ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}

          build-args: |
            RUNTIME=${{ github.event.inputs.runtime || 'hackmdio/runtime:16.20.2-35fe7e39' }}
            BUILDPACK=${{ github.event.inputs.buildpack || 'hackmdio/buildpack:16.20.2-35fe7e39' }}
